name: Nim CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest}
          - {os: macos-latest}
          - {os: windows-latest}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nim
        uses: jiro4989/setup-nim-action@v2
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install deps
        run: nimble install -y
      - name: Run tests
        run: nimble test -y
      - name: Run bench 
        run: nimble bench -y
